apiVersion: v1
name: fluent-bit
description: A Helm chart for Fluent-Bit. A Fast and lightweight log processor and forwarder or Linux, OSX and BSD family operating systems.
version: 0.15.14
appVersion: 1.7.8
icon: https://fluentbit.io/assets/img/logo1-default.png
home: https://github.com/platform9/helm-charts
sources:
  - https://github.com/platform9/helm-charts

