apiVersion: v2
name: nginx-ingress
description: A Helm chart for NGINX Ingress Controller
type: application
version: 0.1.0
appVersion: "1.11.1"
home: https://github.com/platform9/helm-charts
sources:
  - https://github.com/platform9/helm-charts
