apiVersion: v1
kind: Pod
metadata:
  name: hook-postinstall
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  containers:
  - name: hook2-container
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo post-install hook Pod is running - hook-postinstall && sleep 60']
  restartPolicy: Never
  terminationGracePeriodSeconds: 0